### ISSUE TITLE
How do I Extract this to one html page

### ISSUE THREAD

**Issue by Narulacodes** [Narulacodes/proxy#1]

**Comment by GreenBayRules** [comment]
Just make an index.html file. Then have an element in it that says `<div id="result"></div>` then in the JS after you get the JSON do `document.getElementById("result").innerHTML = result;` where `result` is the answer from the httprequest

**Comment by Narulacodes** [comment]
And Will it show the text/Proxy of featurted projects? Thanks BTW!

**Comment by GreenBayRules** [comment]
It should, if you do it properly

**Comment by Narulacodes** [comment]
I did
